# Generated by Django 4.0.4 on 2022-04-28 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_transaction',
            name='total_amount',
        ),
        migrations.CreateModel(
            name='Client_Total_Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField()),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banking.account')),
            ],
        ),
    ]
