# Generated by Django 4.0.4 on 2022-04-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_remove_client_transaction_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_transaction',
            name='available_balance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
