# Generated by Django 4.0.4 on 2022-04-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_alter_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='total_amount',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Client_Total_Amount',
        ),
    ]
