# Generated by Django 4.0.4 on 2022-05-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_account_total_amount_delete_client_total_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client_transaction',
            options={'verbose_name_plural': 'client transaction'},
        ),
        migrations.AlterField(
            model_name='account',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
