# Generated by Django 4.0.4 on 2016-05-02 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_resetpassword_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resetpassword',
            options={'verbose_name_plural': 'Reset Password'},
        ),
    ]
